### Create product
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Тушь",
  "description": "тушь тушь тушь",
  "price": 799,
  "stock": 27,
  "imageUrl": "https://placehold.co/400x400?text=Mascara",
  "category": {
    "id": 1
  },
  "seller": {
    "id": 15
  }
}